### ISSUE TITLE
Add debug versions of assert_relative_eq! and friends

### ISSUE THREAD

**Issue by michael-p** [brendanzab/approx#24]
It would be great to have `debug_assert_{relative|ne}_{eq|ne}` macros that are only checked in non optimized builds, similar to `debug_assert!` from the standard library.

Implementation should be straightforward, something like:
```rust
macro_rules! debug_assert_relative_eq {
    ($($arg:tt)*) => (if cfg!(debug_assertions) { assert_relative_eq!($($arg)*); })
}
```

**Comment by jonaspleyer** [comment]
Hey @michael-p  I have just released a new RC 0.6.0-rc1 which includes many new features. Is this feature request still up to date? More generally speaking: There have also been other questions regarding error reporting and I have decided to bundle them into a new issue.

https://github.com/brendanzab/approx/issues/95

**Comment by michael-p** [comment]
Hi Jonas! This issue is still valid, and I personally don't think it is related to the other issues in #95 but of course would leave this up to you how you want to structure things.

BTW, thank you very much for taking over maintaining this crate! Greetings from Freiburg ;)

**Comment by jonaspleyer** [comment]
Please take a look at the linked PR and share what you think ☺️

**Comment by michael-p** [comment]
Seems ok to me. I only have a use for the assertion-macros (i.e. `debug_assert_relative_eq`) and not the expression-like ones (`debug_relative_eq`, ...) and can't really think of a situation where one might need the later, but maybe there is one, I don't know.

On an unrelated note: adding these macros is not a breaking change, so you would not need to bump the version of the crate to 0.6. Maybe you need that because of other changes but keep in mind that this crate is very widely used and will cause lot's of churn when it upgrades in a non-backward compatible way (i.e. lot's of other crates like `nalgebra` will also need to publish new versions in order for approx version 0.6 to become usable).

**Comment by jonaspleyer** [comment]
I have added the debug macros in the new `0.6.0-rc2` release candidate. I would be very happy about feedback!
